spring.application.name=tracker

# DB config
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/trackthree}
spring.datasource.username=${DATABASE_USERNAME:trackuser}
spring.datasource.password=${DATABASE_PASSWORD:trackpass}

# Hibernate config
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect